#
#name: Build
#
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#
#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#    
#    steps:
#    - uses: actions/checkout@v2
#    - name: Use Node.js
#      uses: actions/setup-node@v2
#      with:
#        node-version: 16.x
#    - run: npm install --no-optional
#    - run: npm run build
#    - name: Archive artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: dist
#        path: |
#          dist
#        retention-days: 1
#